import { Saira, Iceberg, New_Rocker } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer/Footer";
import NProgressProvider from "./providers/NProgressProvider";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const saira = Saira({
  subsets: ["latin"],
  variable: "--font-saira",
  weight: ["400", "700"], // u need which weights
});

const iceBerg = Iceberg({
  subsets: ["latin"],
  variable: "--font-iceBerg",
  weight: ["400"], // u need which weights
});
const newRocker = New_Rocker({
  subsets: ["latin-ext"],
  variable: "--font-newRocker",
  weight: ["400"], // u need which weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${saira.className}}  antialiased`}>
        <Navbar />
        <NProgressProvider>
          {" "}
          {children}
          <ToastContainer position="top-right" autoClose={3000} />
        </NProgressProvider>
        <Footer />
      </body>
    </html>
  );
}
